services:
  capitegory-front:
    container_name: capitegory-front
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  capitegory-backend:
    container_name: capitegory-back
    image: ${DOCKER_REGISTRY-}capitegorybackend
    build:
      context: back-end/CAPItegory_backend
      dockerfile: Dockerfile
      target: final
    environment:
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}

  capitegory-sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: capitegory-sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}